### ISSUE TITLE
Goxlr mic not working

### ISSUE THREAD

**Issue by aaronr7734** [Adelenade/GoXlr-Macos#14]
Hi.
I have a Macbook pro with an M1 Max and a GoXLR.  Whenever I try to record with the Goxlr Mic, I hear nothing.  It is not muted.
I've installed the goxlr-daemon and goxlr-client as well as the latest version of this app, 
the closest thing to an error I've received is from the goxlr-daemon which says:
09:11:21 [WARN] Unable to create path: /usr/share/goxlr/profiles/: Could not create profile directory at /usr/share/goxlr/profiles/
Which makes sense.  Not even sudo permissions will let me do that. However, my config file for goxlr-daemon lists a different path for profiles and the goxlr-client is able to load them, so I don't think the issues are related.
I also know the drivers are able to manipulate the Goxlr, because when I load my goxlr profile, my faders move.
I was able to set up the audio devices from the GoXLR Mac app and those are working perfectly.
I thought I might be able to fix the problem by rebooting, but it's made it worse, as now the Goxlr Mac app won't detect my GoXLR at all, though again, the faders and audio still work.
The Goxlr app just says Connect your GoXlr to get started
 now.
Any ideas on what I can try next?
Thanks!

**Comment by Adelenade** [comment]
Hey ! Just one thing before I can maybe answer you more precisely: by latest version you mean v1.0.0-alpha or a earlier version ?

**Comment by aaronr7734** [comment]
Hi.
Yep, version
V1 Alpha 1.

**Comment by Adelenade** [comment]
Ok ! Nice, so you are on macos Ventura beta ! As i'm on the same version as you it's easier than debugging older versions xD

But if I understand correctly, everything works well (the error failed to create is totally OK, you can ignore it), but when selecting your mic (so the input device named GoXlr) you have no sound ?

First, make sure it's not an routing error of course, or an error with your mic settings.
Also, can you try to put the fader assigned to your mic in "meter" lightning mode ? It will help ensure that it's not a problem with the goxlr itself or with your mic. (you can do it by using this command: `goxlr-client lightning fader <a/b/c/d, fader assigned to your mic> meter`)
And go to mic setup (click on the first "module" of the mic tab) to look if the app is normally displaying your mic level !

**Comment by aaronr7734** [comment]
Hi.
I just made sure the router was set up correctly with the following
commands:
goxlr-client router microphone broadcast-mix true
goxlr-client router microphone chat-mix true
I have monitoring turned on, so I should be hearing my voice from my
headphones, but I'm not.
I can't check the goxlr app because it's not detecting my Goxlr anymore,
though again, it did briefly work after installing the app.

**Comment by Adelenade** [comment]
The new home tab isn't functioning ! If the app doesn't crash at starting then the goxlr is connected, and if the client detect it then the app too !

**Comment by aaronr7734** [comment]
I'm a bit confused about what you wanted me to try.  What's lightning?  If
you mean lighting, the command you gave me didn't work.
If yuou want, go ahead and message me on discord @Aaron_Stormerr#0001

**Comment by Adelenade** [comment]
Of course ! You can go to the support server at https://discord.gg/cyavp8F2WW !

**Comment by Adelenade** [comment]
Closed as moved to discord support server, can be re-opened if this is a app problem and not specific installation problem
