### ISSUE TITLE
Unable to Scroll across Mixer

### ISSUE THREAD

**Issue by kiakri** [Adelenade/GoXlr-Macos#21]
**Describe the bug**

**To Reproduce**

Go to Mixer
Observe other additional options for Channels
Unable to move across. 

**Expected behavior**
Be able to move across to different options, I'm not entirely sure how many are included but i believe mic monitor should be their as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/7399660/195869437-5b34dee1-6879-4b4a-a8b4-745151cc7684.png)

**Desktop (please complete the following information):**
 - Device [e.g. MacBook pro M1 max] M1 Max
 - GoXlr model [e.g. full, mini] Full
 - Version of the app [e.g. 0.3.3] V1 Alpha 3

**Additional context**

**Comment by Adelenade** [comment]
Hi again ! 
I tried to reproduce this bug and i can scroll through the channels :(

If I understand correctly, you can't scroll across the different sliders ?
Here is what i get :

![Screen Recording 2022-10-14 at 16 26 02](https://user-images.githubusercontent.com/63637808/195871318-7c88bd07-6ff2-4f5d-958e-21702ed41325.gif)

Are you sure you scroll horizontally and not vertically ? And have you tried to drag the scroll view ? :0

**Comment by kiakri** [comment]
Mine seems super, duper laggy compared to that Screenshot, everything take ages to update.

**Comment by Adelenade** [comment]
Oh, i know there is a weird bug on the app that makes the whole thing laggy af but it's strange that i can perfectly scroll on an i5 and it's laggy on an m1 max...
That's really a weird thing as i don't really understand where i can optimise anything, i ran some tests and even a minimal custom slider with no special behaviour is making the app slow after some time dragging it <_>

**Comment by kiakri** [comment]
Yeah i can't drag at all on that setting. 

https://user-images.githubusercontent.com/7399660/195874067-85c7cc98-d2fb-45c3-b891-076ad4476309.mov

**Comment by Adelenade** [comment]
Yeah you can't drag i tested it, it's normal, but yeah this is too laggy and i really don't know why so it may be fixed in future releases (not it may, it's the next thing i HAVE to work on <_>) but yeah need to figure out why the fuck it's doing that
