### ISSUE TITLE
Import Mic profile from GoXLR windows app + Created audio routes don't work

### ISSUE THREAD

**Issue by DavidIlie** [Adelenade/GoXlr-Macos#5]
Really nice project, I am now considering switching to Apple (Apple Silicon in fact) as my main workstation if I can get a basic level of functionalities working which from what I've seen is perfectly possible with this software.

Anyway, the system that I am currently using is a M1 Macbook Pro 13 inch with the latest version of macOS Monterey installed. The main problem is that the created audio channels don't work, to the extent of that they are there but nothing outputs through them to the headphones. Hopefully, that is an easy fix.

<img width="657" alt="Screen Shot 2022-06-19 at 17 09 02" src="https://user-images.githubusercontent.com/47594764/174487792-04ddd593-c0d5-46f8-a34a-334d382f307a.png">

Otherwise, I would like to see if it would be possible to apply the .goxlrMicProfile and configure my microphone correctly with my settings.

Thanks!

**Comment by Adelenade** [comment]
Hi ! First, I have to thank you for creating this issue ! 
Yup that's a problem i have sometimes, the GoXlr seems to change its audio object ID so i have to re-configure the sound outputs. But you seem to have an other problem: here the outputs seems to be redirecting audio to the headphones. I think about a problem that can explain this issue.

When you click on create audio outputs, do the default output device of the system is the goxlr ? If it's the headphones, the app will try to create audio outputs for the goxlr... that redirects to the headphones... That's a "problem" I need to fix for the next release (that will take some time because i'm trying to re-write the app from the ground and i'm stuck in a problem of unix socket...).

If you selected well the goxlr as default output when creating the output channels, i'm interested to see a screen of the "Audio Midi Setup" page for one of theses non-functional devices.


Also, to load a goxlr mic profile, i don't think it's possible with the built-in version of the utility, but you can try this command when the app is running:

`/Applications/GoXlr\ Panel.app/Contents/Resources/goxlr-client --load-mic-profile ThePathOfTheProfile(without the .goxlrMicProfile)`

I'm actually trying to add support of audio outputs (mic, broadcast) so i'm not actually working on add all the mic options to the UI but it's planned !

Keep me informed !

**Comment by DavidIlie** [comment]
Hello, Sorry for the late reply. I didn't have access to a Mac but now I have Hackintosh-ed my main computer so I can do more testing.

When I first installed the tool everything worked correctly, I was successfully able to load the microphone profile and also my color scheme from Windows. The different audio channels worked and I was able to play audio in the right channel (By the way, do you know how to route apps such as Spotify to the music channel and leave everything else the same?)

However, there are two problems, the first one is from what I can see in the preview is that every single input channel receives every single GoXLR audio channel meaning that desktop audio is being sent to the Chat Mic audio input. The second problem is that now that I have rebooted the system, the audio outputs are not there, and when I try to create them nothing happens, and I don't have access to the different audio channels.

Here is the "Audio MIDI Setup" you asked for:
![Screen Shot 2022-06-21 at 3 50 28 PM](https://user-images.githubusercontent.com/47594764/174816007-157d3740-8111-4907-8542-4622d1bb5366.png)
Thanks for the help so far!

**Comment by Adelenade** [comment]
Hey ! Before i can answer you, can you put a screen of the audio midi setup of for example the System device ? I think i know what's going on but i want to be sure xD

**Comment by Adelenade** [comment]
Oh it's just a problem of routing ! I thought it was a problem with the channels directly sorry xD

Is the routing section of the app working properly ? Or is there any problem with it ? 
If it's working you're able to check and change the routing in this section, and save your profile with the toolbar button.

**Comment by DavidIlie** [comment]
The Chat audio channel only has Mic Chat and Samples but I can also hear the system audio

![image](https://user-images.githubusercontent.com/47594764/174829433-1423480b-4d1f-4b4d-a077-ca94e32877f1.png)

**Comment by DavidIlie** [comment]
I see, so then how do I modify the broadcast mix channel to only output the microphone?

The other problem I said earlier is that outputs seemed to work but that's just because I was using the default System. But I just tried as a test to switch to music and the audio channel on the GoXLR didn't switch.

**Comment by Adelenade** [comment]
You can do it by applying the routing of the chat mix to the broadcast mix !

And for the other problem, it's really strange... If when you're clicking configure speakers on the music it says that left is Music L and right Music R.... The app by itself does nothing more than creating outputs and tell the system to redirect sound from the newly-created device to the right channels of the goxlr so...

**Comment by DavidIlie** [comment]
What do you mean by "applying the routing of the chat mix to the broadcast mix".

As for the output problem, in the MIDI test option, the different audio channels work. But then when it comes to other applications and system preferences it doesn't work. Could it be a problem with macOS?

**Comment by Adelenade** [comment]
Uh.... If you change of tab and go back to the routing page is the changes are still there ? 

If yes, it's normal if you can HEAR desktop audio in your headphones, but if you hear it in the broadcast mix (or the goxlr device as input) there is a problem and you'll have to launch the app within the terminal to see if there is any errors. You can check if the app communicates with the goxlr well by going to the mixer tab and play a bit with the levels (you can see the hardware sliders moving if everything is right)

**Comment by Adelenade** [comment]
AHHH I can see your error !

If you want to use the broadcast mix, you have to select the goxlr device, NOT one of the aggregate device !
I'm sorry that theses devices appear in the inputs list, but i cant do better for now... I'm working on a solution to get this working better !

**Comment by DavidIlie** [comment]
Ahhh okay!!!! I see, I have changed to the GoXLR input and I can still hear everything in the system, hopefully, it's another obvious thing!!

And don't worry about it, this is a very advanced project and I am really impressed? By the way, how do you interact from the Swift Application to the daemon? I might try and build my own electron-based wrapper to look like the GoXLR app :)

**Comment by DavidIlie** [comment]
Here is me doing this with the debug console open:

![image](https://user-images.githubusercontent.com/47594764/174844652-7ac16703-9da4-4f8b-81b4-3cb376670f8f.png)

**Comment by DavidIlie** [comment]
I want to create the same app that you have, but coded with Electron and React just to style it myself haha (as I am a JavaScript web developer), do you have any links or documentation for the goxlr client plugin? It would help a lot!!

I don't understand what you meant though, which route do I have to change then to only have the microphone? Sorry if I am asking the same question again I don't understand :p

**Comment by Adelenade** [comment]
Oh okay ! I linked the repo of the client and the daemon on the readme ! (at the end, it's named goxlr-utility)

And you have to uncheck everything in the stream line, then check only Mic and if you want Samples !

**Comment by Adelenade** [comment]
I really don't know this time... I'm actually using my goxlr with the app and it's perfectly working... If the daemon says that the routing is what you were trying to do, it's more a problem with the system.

Maybe relaunch everything ? I did some tests by my side and it's every time the two first channels that are selected to "be" the goxlr-input, so here this will be the broadcast-mix ?

Sorry for being unhelpfull but i can't tell you more about your problem because i never faced it and i don't see how i could fix this !

**Comment by DavidIlie** [comment]
No worries, I will attempt to restart everything/find solutions. Thank you so much for the help, keep up the good work!

**Comment by DavidIlie** [comment]
Hold on, I think I might found the problem, in the debug logs all the other ones such as:

`goxlr_daemon::device: Setting Routing: Music BroadcastMix false`

Say `BroadcastMix`, whereas with the system or line-in:

`goxlr_daemon::device: Setting Routing: System Sampler true`

But I don't understand because the way I am testing if it is split is by playing music through the Music channel and that is apparently removed from the Broadcast Stream Mix. This might be a problem with the GoXLR-Utility who knows :p

**Comment by Adelenade** [comment]
Then if you select the Stream / Music checkbox and you toggle on it, you'll hear the music inside the broadcast mix ?

And if it's not working and the debug is saying that it toggled on the wrong route, then i'll have to re-re-re-check every single button of the routing view to check if there is any problem

**Comment by Adelenade** [comment]
So this is just a problem that i didn't had with the goxlr device directly... Maybe the hackintosh, maybe another thing ?

**Comment by DavidIlie** [comment]
I don't think that could be an issue, as it's just an USB device, but I will try now with a M1 Macbook Pro.

**Comment by Adelenade** [comment]
Hmmmmm, yup, maybe just the goxlr audio device means for the system chat mix or an other channel ?

You can try in the meanwhile to uncheck EVERY checkboxes (i think you can keep the checkboxes of the headphones) and see if it changes ?

And is the goxlr input device is playing sound for the music and/or the system or it's just playing music ?

**Comment by DavidIlie** [comment]
Just tried it on my M1 Macbook, same setup as my Hackintosh, and the same problem...

On my Hackintosh I am usiing SoundSource to redirect Spotify to the Music channel, and that is working perfectly fine. In the CLI I disabled every single audio output to the Broadcast Mix input and I can still hear it in the "GoXLR" input.

I did the same thing on my laptop except for disabling the system audio channel as that is where Spotify is playing, the same problem still occurs:

<img width="1374" alt="Screen Shot 2022-06-21 at 19 05 03" src="https://user-images.githubusercontent.com/47594764/174857681-8660ac3a-d90b-4db3-8c46-378d4a17c008.png">
