### ISSUE TITLE
Any way to map an output to a virtual sound source? 

### ISSUE THREAD

**Issue by brymon68** [Adelenade/GoXlr-Macos#8]
First off, this project is incredible!

I think I know the answer to this question but is there no way (currently) to map an output (such as game, system, etc) to a virtual interface? Basically I am trying to mimic functionality on windows where you can map a slider to Spotify app, a video game, etc.

**Comment by Adelenade** [comment]
Infact yes it's kinda possible ! But only if you spend money for it (or if you break some laws) !

For now, you have to use SoundSource by RogueAmoeba: it's the only "serious" software that i found that can select witch app go to witch output... 

I wish I could bundle a way to do the same thing within the app but i'm already trying WITHOUT ANY SUCCESS :'((((( to add support for the broadcast mix and chat mic !

**Comment by brymon68** [comment]
That makes sense! I actually was already using RogueAmoeba but using trial version so guessing that is why those sources weren't showing up in Goxlr-MacOS. I will give that a try. Thank you so much @Adelenade

**Comment by brymon68** [comment]
So I ended up purchasing RogueAmoeba and perhaps I am doing something wrong but there is just a single audio source listed which is: ```GoXLR```. Not sure if there is another way to map audio sources to sliders?

**Comment by Adelenade** [comment]
Whooops ! Forgot to answer to this ! 

Oh okay ! Do you created the audio outputs (with the button inside the settings tab of the app) ? If yes, so go to "Audio midi setup" app and look for the missing audio devices ! When you find them, if I guessed right, you see something like this:

![image](https://user-images.githubusercontent.com/63637808/179600794-871d9e2b-47f5-4f47-bb56-678564a4d5f9.png)

Then you just have to check the "GoXLR" item you see in the list and uncheck the other grey GoXLR item (normally it's now "Offline Device").

So if it solves your issue then it's a bug with CoreAudio that I have sometimes when I plug my goxlr in ! I don't really know how to fix it because normally the device has the same identity but sometimes it doesn't link to the virtual devices !

**Comment by brymon68** [comment]
Thank you @Adelenade I will try this tonight and follow up.

**Comment by brymon68** [comment]
Hi @Adelenade, 

Following up. Here is what I have so far: 

My audio output settings looks like: 
<img width="674" alt="Screen Shot 2022-07-19 at 8 16 49 AM" src="https://user-images.githubusercontent.com/8397405/179772688-6d36d5a8-885e-4f26-aa3a-014a7261bac3.png">

My 'Audio Midi setup' looks like: 

<img width="1170" alt="Screen Shot 2022-07-19 at 8 15 53 AM" src="https://user-images.githubusercontent.com/8397405/179772836-8215c15a-2765-4c1e-97e9-f0fef9ff800a.png">


Now, when you say: 

>  Do you created the audio outputs (with the button inside the settings tab of the app) ? 

I am not sure which settings app you mean? Sound Source? MacOS system preferences? 

> If yes, so go to "Audio midi setup" app and look for the missing audio devices ! When you find them, if I guessed right, you see something like this:


I am able to create an 'Aggregate Device' in Audio Midi Setup if that is what you mean which looks like this: 

<img width="1309" alt="Screen Shot 2022-07-19 at 8 21 57 AM" src="https://user-images.githubusercontent.com/8397405/179773976-62d7b99c-095d-4909-a72e-b4cd690ef516.png">

 But I still do not see the various channels to output audio to in Sound Source application. 


<img width="641" alt="Screen Shot 2022-07-19 at 8 23 35 AM" src="https://user-images.githubusercontent.com/8397405/179774258-8e640016-279c-403a-80bc-d451e360c964.png">

**Comment by Adelenade** [comment]
Oh then I see, you have to select the goxlr as the system output ( not in sound source ) and then go to the settings tab of the goxlr panel app. There is a button called "create audio outputs", click on that, make sure you selected the goxlr as system output and it will create all the devices for you !

**Comment by brymon68** [comment]
@Adelenade  - That worked!!!! WOOO!!!! This is awesome!!! Do you think this should be reflected in README? I am happy to submit a PR
