### ISSUE TITLE
Noise Gate

### ISSUE THREAD

**Issue by SeanVowles** [Adelenade/GoXlr-Macos#9]
For the most part this application is working well enough for daily use, however, the biggest issue I have is by default GoXLR adds about 50db of noise gate to the microphone. Adjust any of the mic settings causes the app to crash.

One thing I have noticed is the app doesn't have an option to control the noise gate. Unfortunately, the default 50db of gate causes my voice to cut out no matter how loud and clearly I speak into my XLR dynamic microphone (this would probably be a much smaller issue on a condenser mic).

Having an option to set the noise gate would be excellent, but if that's a lot of work, it would be ideal if the app could set the default noise gate to around 15-20db. While that might allow background noise to cut through, conferencing applications such as zoom should be smart enough to remove noise.

**Comment by Adelenade** [comment]
Infact it's a problem that can easily be solved, but for that you'll need to stop using the app to use a CLI while the v2 isn't finished.

The actual version of the app that you are using was published when the daemon that I use to handle mute buttons and direct discussion with the device wasn't fully finished (even now it's not FINISHED but it's a lot more complete) so the app couldn’t do much than quickly change the gain of the mic (if it's not crashing like in your case). But you can install the [goxlr-utility](https://github.com/GoXLR-on-Linux/goxlr-utility) that is bundled into the app but with an old version. 

You'll have to launch the daemon with `goxlr-daemon` and then in another terminal window:

`goxlr-client microphone noise-gate threshold <The value you want to put (between -59 and 0)>`

You can also play a bit with the settings, and then when you're done: `goxlr-client profiles mic save` and `goxlr-client profiles device save`
Now if you restart the goXlr it normally keeps the settings you set. 

This problem will be solved with the v2 (#7) but I have to fully re-write all the app so it may take some time (even if i'm working on it actively). Oh, out of interest, what model do you have ? A mini or a full goXlr ?

**Comment by brymon68** [comment]
Which input source should we be selecting for microphone? 'GoXLR'?

**Comment by SeanVowles** [comment]
@Adelenade - that is such a positive and quick reply! I will look into adjusting these settings in the command line. This is an excellent little project. I'm using the GoXLR Mini.

**Comment by Adelenade** [comment]
Hey ! Just a little update, you can now build the v2_dev last commit, I added the mic tab that brings noise gate support, basic EQ settings (but not for the mini sadly, I have to adapt a bit) & gain / mic type selection !

But It's of course a lot buggy as it's a dev version (you need to start the daemon by yourself as it's not bundled) & not optimised UI for the Mini (normally it's not showing tabs like FX and Sampler but I couldn't test that much xD), for example there is no de-esser in the mini (It's not going to crash but it's not going to change anything lol)

So yup If you absolutely need an UI to configure your mic you can play a bit with it !

**Comment by Adelenade** [comment]
Closed as the #7 fully support mic configuration for full version & mini
